### ISSUE TITLE
Unable to transfer VTHO, and Sync not able to load Ledger key via token wallet https://tokens.vecha.in/#/wallets

### ISSUE THREAD

**Issue by loupiote** [vechain/docs#37]
I am using Sync, with my key on a Ledger Nano X hardware device. I can see my VTHO on Sync, but Sync cannot transfer them out - I can only transfer VET.

Someone suggested using https://tokens.vecha.in/#/wallets

When I go there, it starts Sync, and when Sync tries to import my wallet from the Ledger, it displays the following error message:

Ledger device: INS_NOT_SUPPORTED (0x6d00)

My Ledger Nano X has the latest firmware 1.2.4.1 and I installed the lastest VEChain app on the device.

Is there any working way to transfer my VTHO?

**Comment by XJWX89** [comment]
hi @loupiote  what's the VeChain app version on your device ?

**Comment by loupiote** [comment]
1.0.3

Note: This issue is specific to the Ledger-Nano-X.  I don't have the issue when using a Ledger-Nano-S.

**Comment by XJWX89** [comment]
please upgrade your vechain app .the latest version of vechain app on Ledger X is  1.0.7 .

**Comment by loupiote** [comment]
I'll re-install the app from Ledger Live and check the version. I installed it just a couple of days ago, so maybe the issue is that Ledger has an old app on their website? (apps are installed via the Ledger Live app).

**Comment by XJWX89** [comment]
don't forget to uninstall the app first and then re-install the vechain app via ledger live.  

Note : **before the installation please make sure you have the mnemonic phrases.** 

ref : [Ledger device Trouble Shooting ](https://docs.vechain.org/sync/user-guide/import-ledger.html#troubleshooting)

**Comment by loupiote** [comment]
The VEChain app version on the Ledger website (Ledger Live) is 1.0.3 :(

**Comment by loupiote** [comment]
And By the way, the Ledger Live app incorrectly detects my Ledger Nano X as being a Ledger Nano S.  It's a long-time issue, but should not be a problem since all the Ledger apps are - in principle - compatible between the Ledger Nano S and the Ledger Nano X.

**Comment by loupiote** [comment]
So you should tell Ledger to update their VEChain app, so that Ledger-Nano-X get the latest version that allows VTHO transfers.

I just happened to have an old Ledger Nano S, so I was able to do the transfer, since 1.0.3 works fine on the Nano-S.

**Comment by XJWX89** [comment]
we checked the latest version of nano x & s  on ledger live application , both device latest vechain app version is 1.0.7 . 

I will suggest you to update the ledger live app or contact [ledger support](https://support.ledger.com/hc/requests/new) for further assistance .

**Comment by loupiote** [comment]
Ok, I will update my Ledger Live and check again, and I'll report here.

**Comment by loupiote** [comment]
All right, I can now install 1.0.7. It's a shame that Ledger Live does not auto-update or at least inform the user that a newer version is available. It would have saved me (and others) so much time!
Thanks again for your help, I appreciate!

**Comment by XJWX89** [comment]
👍  happy to hear that you solved the problem .  if you are facing another problem you can check out this link [Ledger device trouble shooing](https://docs.vechain.org/sync/user-guide/import-ledger.html#troubleshooting)
