### ISSUE TITLE
PLEASE HELP! I Sent 250,000 VET (VeChain) coins to Atomic Wallet ETH address

### ISSUE THREAD

**Issue by JKWBTC** [vechain/docs#60]
Hello,

Can you help me recover my 250 ,000 VET (VeChain) I sent to Atomic Wallet ETH address from my Ledger Nano X?
Below I will enclose screenshots where I transferred my VET's. hope it will help. I'd appreciate a step-by-step instruction how to transfer them back to my Ledger nano X or to another wallet (i.e. MEW Wallet, Trust Wallet, or Guarda Wallet).

As you see below I my Atomic Wallet shows only 295,1316 VET's. It should show 250,295,1316.
![Atomic Wallet](https://user-images.githubusercontent.com/77935118/106052687-dd1ed880-60b7-11eb-8ac9-626d25674af7.JPG)

In my Ledger Nano X, I have left 200,000 VET's. 
![Ledger Nano X](https://user-images.githubusercontent.com/77935118/106053098-61715b80-60b8-11eb-95d7-291240dd1240.JPG)
![1A](https://user-images.githubusercontent.com/77935118/106053291-a4cbca00-60b8-11eb-8560-62ea41ff2ff0.jpg)

Here is the the ETH wallet address I transferred 100 and 249,990 VETs to:
0x2C0ecad05231389c08CF3f981ba3baACFFd9E73E

![ETH Wallet Address](https://user-images.githubusercontent.com/77935118/106054259-c2e5fa00-60b9-11eb-86c2-263c0ac228e0.jpg)

Now see screenshots of transfers to the above ETH wallet address:
![3A](https://user-images.githubusercontent.com/77935118/106053728-228fd580-60b9-11eb-8d3a-818737329704.JPG)
![4A](https://user-images.githubusercontent.com/77935118/106053824-3c311d00-60b9-11eb-9d9b-1aed88410a0d.JPG)

If you can, please reply to my email address at: jkwbtc@protonmail.com

If you need any additional information, please do not hesitate to ask. Thank you.

John

**Comment by XJWX89** [comment]
You can import your atomic wallet keystore / private into sync then you should see your VET . 

If you have any issue with exporting your keystore/private key , you should contact atomic wallet to ask for support.

**Comment by JKWBTC** [comment]
I was able to recover my VET's! THANK YOU VERY MUCH!

JW

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by XJWX89** [comment]
happy to hear that  👍  have a pleasant day
