### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by sinanouri** [vechain/docs#89]
i get self is not defined error at beginning 

import Connex from '@vechain/connex'
const connex = new Connex({
    node: 'https://mainnet.veblocks.net/', // veblocks public node, use your own if needed
    network: 'main' // defaults to mainnet, so it can be omitted here
})

result:

/home/node_modules/@vechain/connex/dist/connex.js:10
})(self, function() {
   ^

ReferenceError: self is not defined

**Comment by Talented-Developer** [comment]
I got the same issue today, I am now using the version of @2.0.9.
It was released after this issue opened.
I would like to get help from vechain development team!

**Comment by libotony** [comment]
You might be using `@vechain/connex` in Node.js Environment, take a look at https://github.com/vechain/connex/tree/master/packages/connex#using-in-nodejs-environment . And if you still have further questions, I would recommend moving our discussion to repo [vechain/connex](https://github.com/vechain/connex/issues)

**Comment by Talented-Developer** [comment]
Got it.
Thank you very much
